// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type DeleteManufactureResult struct {
	IsDeleted bool   `json:"isDeleted"`
	Message   string `json:"message"`
}

type Manufacture struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt,omitempty"`
}

type ManufactureFilter struct {
	// Наименование производителя поиск.
	NameLike *string `json:"nameLike,omitempty"`
	// Поиск по идентификаторам.
	IdsIn []string `json:"idsIn,omitempty"`
}

type ManufacturePage struct {
	Manufactures []*Manufacture `json:"manufactures"`
	TotalCount   int            `json:"totalCount"`
	NextPage     bool           `json:"nextPage"`
}

type Mutation struct {
}

type Query struct {
}

type Recipe struct {
	ID     string `json:"id"`
	UserID int    `json:"userId"`
	Title  string `json:"title"`
	// Composition of the mix: which tobacco and in which percentage.
	Tobaccos []*RecipeTobacco `json:"tobaccos"`
	// Ordered preparation steps.
	Steps     []*RecipeStep `json:"steps"`
	CreatedAt string        `json:"createdAt"`
	UpdatedAt string        `json:"updatedAt"`
	DeletedAt *string       `json:"deletedAt,omitempty"`
}

type RecipeFilter struct {
	// Filter by author.
	UserID *int `json:"userId,omitempty"`
	// Filter by tobacco in the mix.
	TobaccoIDIn []string `json:"tobaccoIdIn,omitempty"`
}

type RecipeStep struct {
	StepNumber int `json:"stepNumber"`
	// Tobacco the step refers to; empty when the step concerns the whole mix.
	TobaccoID *string `json:"tobaccoId,omitempty"`
	WhatDo    string  `json:"whatDo"`
}

type RecipeStepInput struct {
	StepNumber int     `json:"stepNumber"`
	TobaccoID  *string `json:"tobaccoId,omitempty"`
	WhatDo     string  `json:"whatDo"`
}

type RecipeTobacco struct {
	TobaccoID string `json:"tobaccoId"`
	// Percentage of the tobacco in the mix, e.g. 33.33.
	Percent float64 `json:"percent"`
}

type RecipeTobaccoInput struct {
	TobaccoID string  `json:"tobaccoId"`
	Percent   float64 `json:"percent"`
}

type Tobacco struct {
	ID          string       `json:"id"`
	Taste       string       `json:"taste"`
	Photo       string       `json:"photo"`
	Manufacture *Manufacture `json:"manufacture,omitempty"`
	CreatedAt   string       `json:"createdAt"`
	UpdatedAt   string       `json:"updatedAt"`
	DeletedAt   *string      `json:"deletedAt,omitempty"`
}

type TobaccoFilter struct {
	Taste          *string  `json:"taste,omitempty"`
	ManufactureIds []string `json:"manufactureIds,omitempty"`
}

type User struct {
	ID         int    `json:"id"`
	TelegramID int    `json:"telegramId"`
	NickName   string `json:"nickName"`
	Name       string `json:"name"`
}
