package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	likewhat "github.com/Parnishkaspb/LikeWhatGraphQL/pkg/like_what"
)

// CreateTobacco is the resolver for the createTobacco field.
func (r *mutationResolver) CreateTobacco(ctx context.Context, taste string, photo *string, manufactureID string) (*Tobacco, error) {
	req := &likewhat.CreateTobaccoRequest{
		Taste:         taste,
		ManufactureId: manufactureID,
	}
	if photo != nil {
		req.Photo = *photo
	}

	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Tobacco.CreateTobacco(callCtx, req)
	if err != nil {
		return nil, fmt.Errorf("CreateTobacco: %w", err)
	}
	return protoTobacco(resp), nil
}

// CreateManufacture is the resolver for the createManufacture field.
func (r *mutationResolver) CreateManufacture(ctx context.Context, name string) (*Manufacture, error) {
	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Manufacture.CreateManufacture(callCtx, &likewhat.CreateManufactureRequest{
		Name: name,
	})
	if err != nil {
		return nil, fmt.Errorf("CreateManufacture: %w", err)
	}
	return protoManufacture(resp), nil
}

// EditManufacture is the resolver for the editManufacture field.
func (r *mutationResolver) EditManufacture(ctx context.Context, id string, name string) (*Manufacture, error) {
	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Manufacture.EditManufacture(callCtx, &likewhat.EditManufactureRequest{
		Id:   id,
		Name: name,
	})
	if err != nil {
		return nil, fmt.Errorf("EditManufacture: %w", err)
	}
	return protoManufacture(resp), nil
}

// DeleteManufacture is the resolver for the deleteManufacture field.
func (r *mutationResolver) DeleteManufacture(ctx context.Context, id string) (*DeleteManufactureResult, error) {
	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Manufacture.DeleteManufacture(callCtx, &likewhat.DeleteManufactureRequest{
		Id: id,
	})
	if err != nil {
		return nil, fmt.Errorf("DeleteManufacture: %w", err)
	}
	return &DeleteManufactureResult{
		IsDeleted: resp.IsDeleted,
		Message:   resp.Message,
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, telegramID int, nickName string, name string) (*User, error) {
	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.User.CreateUser(callCtx, &likewhat.CreateUserRequest{
		TelegramId: int64(telegramID),
		NickName:   nickName,
		Name:       name,
	})
	if err != nil {
		return nil, fmt.Errorf("CreateUser: %w", err)
	}
	return protoUser(resp), nil
}

// CreateRecipe is the resolver for the createRecipe field.
func (r *mutationResolver) CreateRecipe(ctx context.Context, userID int, title string, tobaccos []*RecipeTobaccoInput, steps []*RecipeStepInput) (*Recipe, error) {
	reqTobaccos := make([]*likewhat.RecipeTobacco, 0, len(tobaccos))
	for _, t := range tobaccos {
		reqTobaccos = append(reqTobaccos, &likewhat.RecipeTobacco{
			TobaccoId: t.TobaccoID,
			Percent:   t.Percent,
		})
	}

	reqSteps := make([]*likewhat.RecipeStep, 0, len(steps))
	for _, s := range steps {
		step := &likewhat.RecipeStep{
			StepNumber: int64(s.StepNumber),
			WhatDo:     s.WhatDo,
		}
		if s.TobaccoID != nil {
			step.TobaccoId = *s.TobaccoID
		}
		reqSteps = append(reqSteps, step)
	}

	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Recipe.CreateRecipe(callCtx, &likewhat.CreateRecipeRequest{
		UserId:    int64(userID),
		Title:     title,
		Tobaccos:  reqTobaccos,
		Steps:     reqSteps,
	})
	if err != nil {
		return nil, fmt.Errorf("CreateRecipe: %w", err)
	}
	return protoRecipe(resp), nil
}

// Tobacco is the resolver for the tobacco field.
func (r *queryResolver) Tobacco(ctx context.Context, id string) (*Tobacco, error) {
	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Tobacco.GetTobacco(callCtx, &likewhat.GetTobaccoRequest{Id: id})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, fmt.Errorf("tobacco %q not found", id)
		}
		return nil, fmt.Errorf("GetTobacco: %w", err)
	}
	return protoTobacco(resp), nil
}

// Tobaccos is the resolver for the tobaccos field.
func (r *queryResolver) Tobaccos(ctx context.Context, filter *TobaccoFilter) ([]*Tobacco, error) {
	req := &likewhat.ListTobaccosRequest{}
	if filter != nil {
		if filter.Taste != nil {
			req.Taste = *filter.Taste
		}
		if filter.ManufactureIds != nil {
			req.ManufactureId = filter.ManufactureIds
		}
	}

	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Tobacco.ListTobaccos(callCtx, req)
	if err != nil {
		return nil, fmt.Errorf("ListTobaccos: %w", err)
	}

	res := make([]*Tobacco, 0, len(resp.Tobaccos))
	for _, t := range resp.Tobaccos {
		res = append(res, protoTobacco(t))
	}
	return res, nil
}

// Manufactures is the resolver for the manufactures field.
func (r *queryResolver) Manufactures(ctx context.Context, filter *ManufactureFilter, perPage *int, page *int) (*ManufacturePage, error) {
	req := &likewhat.ListManufacturesRequest{}
	if filter != nil {
		f := &likewhat.ListManufacturesRequest_Filter{}
		if filter.NameLike != nil {
			f.NameLike = *filter.NameLike
		}
		if filter.IdsIn != nil {
			f.IdsIn = filter.IdsIn
		}
		req.Filter = f
	}
	if perPage != nil {
		req.PerPage = uint64(*perPage)
	}
	if page != nil {
		req.Page = uint64(*page)
	}

	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Manufacture.ListManufactures(callCtx, req)
	if err != nil {
		return nil, fmt.Errorf("ListManufactures: %w", err)
	}

	manufactures := make([]*Manufacture, 0, len(resp.Manufactures))
	for _, m := range resp.Manufactures {
		manufactures = append(manufactures, protoManufacture(m))
	}
	return &ManufacturePage{
		Manufactures: manufactures,
		TotalCount:   int(resp.TotalCount),
		NextPage:     resp.NextPage,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id int) (*User, error) {
	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.User.GetUser(callCtx, &likewhat.GetUserRequest{Id: int64(id)})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, fmt.Errorf("user %d not found", id)
		}
		return nil, fmt.Errorf("GetUser: %w", err)
	}
	return protoUser(resp), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.User.ListUsers(callCtx, &likewhat.ListUsersRequest{})
	if err != nil {
		return nil, fmt.Errorf("ListUsers: %w", err)
	}

	res := make([]*User, 0, len(resp.Users))
	for _, u := range resp.Users {
		res = append(res, protoUser(u))
	}
	return res, nil
}

// Recipe is the resolver for the recipe field.
func (r *queryResolver) Recipe(ctx context.Context, id string) (*Recipe, error) {
	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Recipe.GetRecipe(callCtx, &likewhat.GetRecipeRequest{Id: id})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, fmt.Errorf("recipe %q not found", id)
		}
		return nil, fmt.Errorf("GetRecipe: %w", err)
	}
	return protoRecipe(resp), nil
}

// Recipes is the resolver for the recipes field.
func (r *queryResolver) Recipes(ctx context.Context, filter *RecipeFilter) ([]*Recipe, error) {
	req := &likewhat.ListRecipesRequest{}
	if filter != nil {
		f := &likewhat.ListRecipesRequest_Filter{}
		if filter.UserID != nil {
			f.UserId = int64(*filter.UserID)
		}
		if filter.TobaccoIDIn != nil {
			f.TobaccoIdIn = filter.TobaccoIDIn
		}
		req.Filter = f
	}

	callCtx, cancel := r.Clients.CallCtx(ctx)
	defer cancel()

	resp, err := r.Clients.Recipe.ListRecipes(callCtx, req)
	if err != nil {
		return nil, fmt.Errorf("ListRecipes: %w", err)
	}

	res := make([]*Recipe, 0, len(resp.Recipes))
	for _, rec := range resp.Recipes {
		res = append(res, protoRecipe(rec))
	}
	return res, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
