// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: like_what.proto

package likewhat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tobacco struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Taste         string                 `protobuf:"bytes,2,opt,name=taste,proto3" json:"taste,omitempty"`
	Photo         string                 `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	Manufacture   *Manufacture           `protobuf:"bytes,4,opt,name=manufacture,proto3" json:"manufacture,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tobacco) Reset() {
	*x = Tobacco{}
	mi := &file_like_what_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tobacco) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tobacco) ProtoMessage() {}

func (x *Tobacco) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tobacco.ProtoReflect.Descriptor instead.
func (*Tobacco) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{0}
}

func (x *Tobacco) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tobacco) GetTaste() string {
	if x != nil {
		return x.Taste
	}
	return ""
}

func (x *Tobacco) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *Tobacco) GetManufacture() *Manufacture {
	if x != nil {
		return x.Manufacture
	}
	return nil
}

func (x *Tobacco) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tobacco) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Tobacco) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreateTobaccoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taste         string                 `protobuf:"bytes,1,opt,name=taste,proto3" json:"taste,omitempty"`
	Photo         string                 `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`
	ManufactureId string                 `protobuf:"bytes,3,opt,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTobaccoRequest) Reset() {
	*x = CreateTobaccoRequest{}
	mi := &file_like_what_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTobaccoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTobaccoRequest) ProtoMessage() {}

func (x *CreateTobaccoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTobaccoRequest.ProtoReflect.Descriptor instead.
func (*CreateTobaccoRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTobaccoRequest) GetTaste() string {
	if x != nil {
		return x.Taste
	}
	return ""
}

func (x *CreateTobaccoRequest) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *CreateTobaccoRequest) GetManufactureId() string {
	if x != nil {
		return x.ManufactureId
	}
	return ""
}

type GetTobaccoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTobaccoRequest) Reset() {
	*x = GetTobaccoRequest{}
	mi := &file_like_what_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTobaccoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTobaccoRequest) ProtoMessage() {}

func (x *GetTobaccoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTobaccoRequest.ProtoReflect.Descriptor instead.
func (*GetTobaccoRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{2}
}

func (x *GetTobaccoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTobaccosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taste         string                 `protobuf:"bytes,1,opt,name=taste,proto3" json:"taste,omitempty"`
	ManufactureId []string               `protobuf:"bytes,2,rep,name=manufacture_id,json=manufactureId,proto3" json:"manufacture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTobaccosRequest) Reset() {
	*x = ListTobaccosRequest{}
	mi := &file_like_what_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTobaccosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTobaccosRequest) ProtoMessage() {}

func (x *ListTobaccosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTobaccosRequest.ProtoReflect.Descriptor instead.
func (*ListTobaccosRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{3}
}

func (x *ListTobaccosRequest) GetTaste() string {
	if x != nil {
		return x.Taste
	}
	return ""
}

func (x *ListTobaccosRequest) GetManufactureId() []string {
	if x != nil {
		return x.ManufactureId
	}
	return nil
}

type ListTobaccosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tobaccos      []*Tobacco             `protobuf:"bytes,1,rep,name=tobaccos,proto3" json:"tobaccos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTobaccosResponse) Reset() {
	*x = ListTobaccosResponse{}
	mi := &file_like_what_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTobaccosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTobaccosResponse) ProtoMessage() {}

func (x *ListTobaccosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTobaccosResponse.ProtoReflect.Descriptor instead.
func (*ListTobaccosResponse) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{4}
}

func (x *ListTobaccosResponse) GetTobaccos() []*Tobacco {
	if x != nil {
		return x.Tobaccos
	}
	return nil
}

type CreateManufactureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManufactureRequest) Reset() {
	*x = CreateManufactureRequest{}
	mi := &file_like_what_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManufactureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManufactureRequest) ProtoMessage() {}

func (x *CreateManufactureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManufactureRequest.ProtoReflect.Descriptor instead.
func (*CreateManufactureRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{5}
}

func (x *CreateManufactureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Manufacture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacture) Reset() {
	*x = Manufacture{}
	mi := &file_like_what_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacture) ProtoMessage() {}

func (x *Manufacture) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacture.ProtoReflect.Descriptor instead.
func (*Manufacture) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{6}
}

func (x *Manufacture) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manufacture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacture) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Manufacture) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Manufacture) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ListManufacturesRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Filter        *ListManufacturesRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PerPage       uint64                          `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Page          uint64                          `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturesRequest) Reset() {
	*x = ListManufacturesRequest{}
	mi := &file_like_what_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturesRequest) ProtoMessage() {}

func (x *ListManufacturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturesRequest.ProtoReflect.Descriptor instead.
func (*ListManufacturesRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{7}
}

func (x *ListManufacturesRequest) GetFilter() *ListManufacturesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListManufacturesRequest) GetPerPage() uint64 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListManufacturesRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListManufacturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufactures  []*Manufacture         `protobuf:"bytes,1,rep,name=manufactures,proto3" json:"manufactures,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPage      bool                   `protobuf:"varint,3,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturesResponse) Reset() {
	*x = ListManufacturesResponse{}
	mi := &file_like_what_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturesResponse) ProtoMessage() {}

func (x *ListManufacturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturesResponse.ProtoReflect.Descriptor instead.
func (*ListManufacturesResponse) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{8}
}

func (x *ListManufacturesResponse) GetManufactures() []*Manufacture {
	if x != nil {
		return x.Manufactures
	}
	return nil
}

func (x *ListManufacturesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListManufacturesResponse) GetNextPage() bool {
	if x != nil {
		return x.NextPage
	}
	return false
}

type EditManufactureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditManufactureRequest) Reset() {
	*x = EditManufactureRequest{}
	mi := &file_like_what_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditManufactureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditManufactureRequest) ProtoMessage() {}

func (x *EditManufactureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditManufactureRequest.ProtoReflect.Descriptor instead.
func (*EditManufactureRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{9}
}

func (x *EditManufactureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditManufactureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteManufactureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManufactureRequest) Reset() {
	*x = DeleteManufactureRequest{}
	mi := &file_like_what_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManufactureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManufactureRequest) ProtoMessage() {}

func (x *DeleteManufactureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManufactureRequest.ProtoReflect.Descriptor instead.
func (*DeleteManufactureRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteManufactureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteManufactureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDeleted     bool                   `protobuf:"varint,1,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManufactureResponse) Reset() {
	*x = DeleteManufactureResponse{}
	mi := &file_like_what_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManufactureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManufactureResponse) ProtoMessage() {}

func (x *DeleteManufactureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManufactureResponse.ProtoReflect.Descriptor instead.
func (*DeleteManufactureResponse) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteManufactureResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *DeleteManufactureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TelegramId    int64                  `protobuf:"varint,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_like_what_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{12}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *User) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_like_what_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUserRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *CreateUserRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_like_what_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_like_what_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{15}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_like_what_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{16}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Recipe struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title  string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Composition of the mix: which tobacco and in which percentage.
	Tobaccos []*RecipeTobacco `protobuf:"bytes,4,rep,name=tobaccos,proto3" json:"tobaccos,omitempty"`
	// Ordered preparation steps.
	Steps         []*RecipeStep          `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipe) Reset() {
	*x = Recipe{}
	mi := &file_like_what_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipe) ProtoMessage() {}

func (x *Recipe) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipe.ProtoReflect.Descriptor instead.
func (*Recipe) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{17}
}

func (x *Recipe) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recipe) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Recipe) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Recipe) GetTobaccos() []*RecipeTobacco {
	if x != nil {
		return x.Tobaccos
	}
	return nil
}

func (x *Recipe) GetSteps() []*RecipeStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Recipe) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Recipe) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Recipe) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type RecipeTobacco struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TobaccoId string                 `protobuf:"bytes,1,opt,name=tobacco_id,json=tobaccoId,proto3" json:"tobacco_id,omitempty"`
	// Percentage of the tobacco in the mix, e.g. 33.33.
	Percent       float64 `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeTobacco) Reset() {
	*x = RecipeTobacco{}
	mi := &file_like_what_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeTobacco) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeTobacco) ProtoMessage() {}

func (x *RecipeTobacco) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeTobacco.ProtoReflect.Descriptor instead.
func (*RecipeTobacco) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{18}
}

func (x *RecipeTobacco) GetTobaccoId() string {
	if x != nil {
		return x.TobaccoId
	}
	return ""
}

func (x *RecipeTobacco) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type RecipeStep struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StepNumber int64                  `protobuf:"varint,1,opt,name=step_number,json=stepNumber,proto3" json:"step_number,omitempty"`
	// Tobacco the step refers to; empty when the step concerns the whole mix.
	TobaccoId     string `protobuf:"bytes,2,opt,name=tobacco_id,json=tobaccoId,proto3" json:"tobacco_id,omitempty"`
	WhatDo        string `protobuf:"bytes,3,opt,name=what_do,json=whatDo,proto3" json:"what_do,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeStep) Reset() {
	*x = RecipeStep{}
	mi := &file_like_what_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeStep) ProtoMessage() {}

func (x *RecipeStep) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeStep.ProtoReflect.Descriptor instead.
func (*RecipeStep) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{19}
}

func (x *RecipeStep) GetStepNumber() int64 {
	if x != nil {
		return x.StepNumber
	}
	return 0
}

func (x *RecipeStep) GetTobaccoId() string {
	if x != nil {
		return x.TobaccoId
	}
	return ""
}

func (x *RecipeStep) GetWhatDo() string {
	if x != nil {
		return x.WhatDo
	}
	return ""
}

type CreateRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tobaccos      []*RecipeTobacco       `protobuf:"bytes,3,rep,name=tobaccos,proto3" json:"tobaccos,omitempty"`
	Steps         []*RecipeStep          `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeRequest) Reset() {
	*x = CreateRecipeRequest{}
	mi := &file_like_what_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest) ProtoMessage() {}

func (x *CreateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{20}
}

func (x *CreateRecipeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateRecipeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRecipeRequest) GetTobaccos() []*RecipeTobacco {
	if x != nil {
		return x.Tobaccos
	}
	return nil
}

func (x *CreateRecipeRequest) GetSteps() []*RecipeStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type GetRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeRequest) Reset() {
	*x = GetRecipeRequest{}
	mi := &file_like_what_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeRequest) ProtoMessage() {}

func (x *GetRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{21}
}

func (x *GetRecipeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRecipesRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Filter        *ListRecipesRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipesRequest) Reset() {
	*x = ListRecipesRequest{}
	mi := &file_like_what_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesRequest) ProtoMessage() {}

func (x *ListRecipesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesRequest.ProtoReflect.Descriptor instead.
func (*ListRecipesRequest) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{22}
}

func (x *ListRecipesRequest) GetFilter() *ListRecipesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListRecipesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipes       []*Recipe              `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipesResponse) Reset() {
	*x = ListRecipesResponse{}
	mi := &file_like_what_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesResponse) ProtoMessage() {}

func (x *ListRecipesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesResponse.ProtoReflect.Descriptor instead.
func (*ListRecipesResponse) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{23}
}

func (x *ListRecipesResponse) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type ListManufacturesRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Наименование производителя поиск.
	NameLike string `protobuf:"bytes,1,opt,name=name_like,json=nameLike,proto3" json:"name_like,omitempty"`
	// Поиск по идентификаторам.
	IdsIn         []string `protobuf:"bytes,2,rep,name=ids_in,json=idsIn,proto3" json:"ids_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturesRequest_Filter) Reset() {
	*x = ListManufacturesRequest_Filter{}
	mi := &file_like_what_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturesRequest_Filter) ProtoMessage() {}

func (x *ListManufacturesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturesRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListManufacturesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListManufacturesRequest_Filter) GetNameLike() string {
	if x != nil {
		return x.NameLike
	}
	return ""
}

func (x *ListManufacturesRequest_Filter) GetIdsIn() []string {
	if x != nil {
		return x.IdsIn
	}
	return nil
}

type ListRecipesRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by author.
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Filter by tobacco in the mix.
	TobaccoIdIn   []string `protobuf:"bytes,2,rep,name=tobacco_id_in,json=tobaccoIdIn,proto3" json:"tobacco_id_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipesRequest_Filter) Reset() {
	*x = ListRecipesRequest_Filter{}
	mi := &file_like_what_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesRequest_Filter) ProtoMessage() {}

func (x *ListRecipesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_like_what_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListRecipesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_like_what_proto_rawDescGZIP(), []int{22, 0}
}

func (x *ListRecipesRequest_Filter) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListRecipesRequest_Filter) GetTobaccoIdIn() []string {
	if x != nil {
		return x.TobaccoIdIn
	}
	return nil
}

var File_like_what_proto protoreflect.FileDescriptor

const file_like_what_proto_rawDesc = "" +
	"\n" +
	"\x0flike_what.proto\x12\blikewhat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\aTobacco\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05taste\x18\x02 \x01(\tR\x05taste\x12\x14\n" +
	"\x05photo\x18\x03 \x01(\tR\x05photo\x127\n" +
	"\vmanufacture\x18\x04 \x01(\v2\x15.likewhat.ManufactureR\vmanufacture\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"i\n" +
	"\x14CreateTobaccoRequest\x12\x14\n" +
	"\x05taste\x18\x01 \x01(\tR\x05taste\x12\x14\n" +
	"\x05photo\x18\x02 \x01(\tR\x05photo\x12%\n" +
	"\x0emanufacture_id\x18\x03 \x01(\tR\rmanufactureId\"#\n" +
	"\x11GetTobaccoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x13ListTobaccosRequest\x12\x14\n" +
	"\x05taste\x18\x01 \x01(\tR\x05taste\x12%\n" +
	"\x0emanufacture_id\x18\x02 \x03(\tR\rmanufactureId\"E\n" +
	"\x14ListTobaccosResponse\x12-\n" +
	"\btobaccos\x18\x01 \x03(\v2\x11.likewhat.TobaccoR\btobaccos\".\n" +
	"\x18CreateManufactureRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xe2\x01\n" +
	"\vManufacture\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xc8\x01\n" +
	"\x17ListManufacturesRequest\x12@\n" +
	"\x06filter\x18\x01 \x01(\v2(.likewhat.ListManufacturesRequest.FilterR\x06filter\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x04R\aperPage\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x1a<\n" +
	"\x06Filter\x12\x1b\n" +
	"\tname_like\x18\x01 \x01(\tR\bnameLike\x12\x15\n" +
	"\x06ids_in\x18\x02 \x03(\tR\x05idsIn\"\x93\x01\n" +
	"\x18ListManufacturesResponse\x129\n" +
	"\fmanufactures\x18\x01 \x03(\v2\x15.likewhat.ManufactureR\fmanufactures\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x1b\n" +
	"\tnext_page\x18\x03 \x01(\bR\bnextPage\"<\n" +
	"\x16EditManufactureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x18DeleteManufactureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x19DeleteManufactureResponse\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x01 \x01(\bR\tisDeleted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\x03R\n" +
	"telegramId\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"e\n" +
	"\x11CreateUserRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\x12\x1b\n" +
	"\tnick_name\x18\x02 \x01(\tR\bnickName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x12\n" +
	"\x10ListUsersRequest\"9\n" +
	"\x11ListUsersResponse\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.likewhat.UserR\x05users\"\xd9\x02\n" +
	"\x06Recipe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x123\n" +
	"\btobaccos\x18\x04 \x03(\v2\x17.likewhat.RecipeTobaccoR\btobaccos\x12*\n" +
	"\x05steps\x18\x05 \x03(\v2\x14.likewhat.RecipeStepR\x05steps\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"H\n" +
	"\rRecipeTobacco\x12\x1d\n" +
	"\n" +
	"tobacco_id\x18\x01 \x01(\tR\ttobaccoId\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\"e\n" +
	"\n" +
	"RecipeStep\x12\x1f\n" +
	"\vstep_number\x18\x01 \x01(\x03R\n" +
	"stepNumber\x12\x1d\n" +
	"\n" +
	"tobacco_id\x18\x02 \x01(\tR\ttobaccoId\x12\x17\n" +
	"\awhat_do\x18\x03 \x01(\tR\x06whatDo\"\xa5\x01\n" +
	"\x13CreateRecipeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x123\n" +
	"\btobaccos\x18\x03 \x03(\v2\x17.likewhat.RecipeTobaccoR\btobaccos\x12*\n" +
	"\x05steps\x18\x04 \x03(\v2\x14.likewhat.RecipeStepR\x05steps\"\"\n" +
	"\x10GetRecipeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x01\n" +
	"\x12ListRecipesRequest\x12;\n" +
	"\x06filter\x18\x01 \x01(\v2#.likewhat.ListRecipesRequest.FilterR\x06filter\x1aE\n" +
	"\x06Filter\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\"\n" +
	"\rtobacco_id_in\x18\x02 \x03(\tR\vtobaccoIdIn\"A\n" +
	"\x13ListRecipesResponse\x12*\n" +
	"\arecipes\x18\x01 \x03(\v2\x10.likewhat.RecipeR\arecipes2\xe1\x01\n" +
	"\x0eTobaccoService\x12B\n" +
	"\rCreateTobacco\x12\x1e.likewhat.CreateTobaccoRequest\x1a\x11.likewhat.Tobacco\x12<\n" +
	"\n" +
	"GetTobacco\x12\x1b.likewhat.GetTobaccoRequest\x1a\x11.likewhat.Tobacco\x12M\n" +
	"\fListTobaccos\x12\x1d.likewhat.ListTobaccosRequest\x1a\x1e.likewhat.ListTobaccosResponse2\xe9\x02\n" +
	"\x12ManufactureService\x12N\n" +
	"\x11CreateManufacture\x12\".likewhat.CreateManufactureRequest\x1a\x15.likewhat.Manufacture\x12Y\n" +
	"\x10ListManufactures\x12!.likewhat.ListManufacturesRequest\x1a\".likewhat.ListManufacturesResponse\x12J\n" +
	"\x0fEditManufacture\x12 .likewhat.EditManufactureRequest\x1a\x15.likewhat.Manufacture\x12\\\n" +
	"\x11DeleteManufacture\x12\".likewhat.DeleteManufactureRequest\x1a#.likewhat.DeleteManufactureResponse2\xc3\x01\n" +
	"\vUserService\x129\n" +
	"\n" +
	"CreateUser\x12\x1b.likewhat.CreateUserRequest\x1a\x0e.likewhat.User\x123\n" +
	"\aGetUser\x12\x18.likewhat.GetUserRequest\x1a\x0e.likewhat.User\x12D\n" +
	"\tListUsers\x12\x1a.likewhat.ListUsersRequest\x1a\x1b.likewhat.ListUsersResponse2\xd7\x01\n" +
	"\rRecipeService\x12?\n" +
	"\fCreateRecipe\x12\x1d.likewhat.CreateRecipeRequest\x1a\x10.likewhat.Recipe\x129\n" +
	"\tGetRecipe\x12\x1a.likewhat.GetRecipeRequest\x1a\x10.likewhat.Recipe\x12J\n" +
	"\vListRecipes\x12\x1c.likewhat.ListRecipesRequest\x1a\x1d.likewhat.ListRecipesResponseB9Z7github.com/Parnishkaspb/LikeWhat/pkg/like_what;likewhatb\x06proto3"

var (
	file_like_what_proto_rawDescOnce sync.Once
	file_like_what_proto_rawDescData []byte
)

func file_like_what_proto_rawDescGZIP() []byte {
	file_like_what_proto_rawDescOnce.Do(func() {
		file_like_what_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_like_what_proto_rawDesc), len(file_like_what_proto_rawDesc)))
	})
	return file_like_what_proto_rawDescData
}

var file_like_what_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_like_what_proto_goTypes = []any{
	(*Tobacco)(nil),                        // 0: likewhat.Tobacco
	(*CreateTobaccoRequest)(nil),           // 1: likewhat.CreateTobaccoRequest
	(*GetTobaccoRequest)(nil),              // 2: likewhat.GetTobaccoRequest
	(*ListTobaccosRequest)(nil),            // 3: likewhat.ListTobaccosRequest
	(*ListTobaccosResponse)(nil),           // 4: likewhat.ListTobaccosResponse
	(*CreateManufactureRequest)(nil),       // 5: likewhat.CreateManufactureRequest
	(*Manufacture)(nil),                    // 6: likewhat.Manufacture
	(*ListManufacturesRequest)(nil),        // 7: likewhat.ListManufacturesRequest
	(*ListManufacturesResponse)(nil),       // 8: likewhat.ListManufacturesResponse
	(*EditManufactureRequest)(nil),         // 9: likewhat.EditManufactureRequest
	(*DeleteManufactureRequest)(nil),       // 10: likewhat.DeleteManufactureRequest
	(*DeleteManufactureResponse)(nil),      // 11: likewhat.DeleteManufactureResponse
	(*User)(nil),                           // 12: likewhat.User
	(*CreateUserRequest)(nil),              // 13: likewhat.CreateUserRequest
	(*GetUserRequest)(nil),                 // 14: likewhat.GetUserRequest
	(*ListUsersRequest)(nil),               // 15: likewhat.ListUsersRequest
	(*ListUsersResponse)(nil),              // 16: likewhat.ListUsersResponse
	(*Recipe)(nil),                         // 17: likewhat.Recipe
	(*RecipeTobacco)(nil),                  // 18: likewhat.RecipeTobacco
	(*RecipeStep)(nil),                     // 19: likewhat.RecipeStep
	(*CreateRecipeRequest)(nil),            // 20: likewhat.CreateRecipeRequest
	(*GetRecipeRequest)(nil),               // 21: likewhat.GetRecipeRequest
	(*ListRecipesRequest)(nil),             // 22: likewhat.ListRecipesRequest
	(*ListRecipesResponse)(nil),            // 23: likewhat.ListRecipesResponse
	(*ListManufacturesRequest_Filter)(nil), // 24: likewhat.ListManufacturesRequest.Filter
	(*ListRecipesRequest_Filter)(nil),      // 25: likewhat.ListRecipesRequest.Filter
	(*timestamppb.Timestamp)(nil),          // 26: google.protobuf.Timestamp
}
var file_like_what_proto_depIdxs = []int32{
	6,  // 0: likewhat.Tobacco.manufacture:type_name -> likewhat.Manufacture
	26, // 1: likewhat.Tobacco.created_at:type_name -> google.protobuf.Timestamp
	26, // 2: likewhat.Tobacco.updated_at:type_name -> google.protobuf.Timestamp
	26, // 3: likewhat.Tobacco.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 4: likewhat.ListTobaccosResponse.tobaccos:type_name -> likewhat.Tobacco
	26, // 5: likewhat.Manufacture.created_at:type_name -> google.protobuf.Timestamp
	26, // 6: likewhat.Manufacture.updated_at:type_name -> google.protobuf.Timestamp
	26, // 7: likewhat.Manufacture.deleted_at:type_name -> google.protobuf.Timestamp
	24, // 8: likewhat.ListManufacturesRequest.filter:type_name -> likewhat.ListManufacturesRequest.Filter
	6,  // 9: likewhat.ListManufacturesResponse.manufactures:type_name -> likewhat.Manufacture
	12, // 10: likewhat.ListUsersResponse.users:type_name -> likewhat.User
	18, // 11: likewhat.Recipe.tobaccos:type_name -> likewhat.RecipeTobacco
	19, // 12: likewhat.Recipe.steps:type_name -> likewhat.RecipeStep
	26, // 13: likewhat.Recipe.created_at:type_name -> google.protobuf.Timestamp
	26, // 14: likewhat.Recipe.updated_at:type_name -> google.protobuf.Timestamp
	26, // 15: likewhat.Recipe.deleted_at:type_name -> google.protobuf.Timestamp
	18, // 16: likewhat.CreateRecipeRequest.tobaccos:type_name -> likewhat.RecipeTobacco
	19, // 17: likewhat.CreateRecipeRequest.steps:type_name -> likewhat.RecipeStep
	25, // 18: likewhat.ListRecipesRequest.filter:type_name -> likewhat.ListRecipesRequest.Filter
	17, // 19: likewhat.ListRecipesResponse.recipes:type_name -> likewhat.Recipe
	1,  // 20: likewhat.TobaccoService.CreateTobacco:input_type -> likewhat.CreateTobaccoRequest
	2,  // 21: likewhat.TobaccoService.GetTobacco:input_type -> likewhat.GetTobaccoRequest
	3,  // 22: likewhat.TobaccoService.ListTobaccos:input_type -> likewhat.ListTobaccosRequest
	5,  // 23: likewhat.ManufactureService.CreateManufacture:input_type -> likewhat.CreateManufactureRequest
	7,  // 24: likewhat.ManufactureService.ListManufactures:input_type -> likewhat.ListManufacturesRequest
	9,  // 25: likewhat.ManufactureService.EditManufacture:input_type -> likewhat.EditManufactureRequest
	10, // 26: likewhat.ManufactureService.DeleteManufacture:input_type -> likewhat.DeleteManufactureRequest
	13, // 27: likewhat.UserService.CreateUser:input_type -> likewhat.CreateUserRequest
	14, // 28: likewhat.UserService.GetUser:input_type -> likewhat.GetUserRequest
	15, // 29: likewhat.UserService.ListUsers:input_type -> likewhat.ListUsersRequest
	20, // 30: likewhat.RecipeService.CreateRecipe:input_type -> likewhat.CreateRecipeRequest
	21, // 31: likewhat.RecipeService.GetRecipe:input_type -> likewhat.GetRecipeRequest
	22, // 32: likewhat.RecipeService.ListRecipes:input_type -> likewhat.ListRecipesRequest
	0,  // 33: likewhat.TobaccoService.CreateTobacco:output_type -> likewhat.Tobacco
	0,  // 34: likewhat.TobaccoService.GetTobacco:output_type -> likewhat.Tobacco
	4,  // 35: likewhat.TobaccoService.ListTobaccos:output_type -> likewhat.ListTobaccosResponse
	6,  // 36: likewhat.ManufactureService.CreateManufacture:output_type -> likewhat.Manufacture
	8,  // 37: likewhat.ManufactureService.ListManufactures:output_type -> likewhat.ListManufacturesResponse
	6,  // 38: likewhat.ManufactureService.EditManufacture:output_type -> likewhat.Manufacture
	11, // 39: likewhat.ManufactureService.DeleteManufacture:output_type -> likewhat.DeleteManufactureResponse
	12, // 40: likewhat.UserService.CreateUser:output_type -> likewhat.User
	12, // 41: likewhat.UserService.GetUser:output_type -> likewhat.User
	16, // 42: likewhat.UserService.ListUsers:output_type -> likewhat.ListUsersResponse
	17, // 43: likewhat.RecipeService.CreateRecipe:output_type -> likewhat.Recipe
	17, // 44: likewhat.RecipeService.GetRecipe:output_type -> likewhat.Recipe
	23, // 45: likewhat.RecipeService.ListRecipes:output_type -> likewhat.ListRecipesResponse
	33, // [33:46] is the sub-list for method output_type
	20, // [20:33] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_like_what_proto_init() }
func file_like_what_proto_init() {
	if File_like_what_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_like_what_proto_rawDesc), len(file_like_what_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_like_what_proto_goTypes,
		DependencyIndexes: file_like_what_proto_depIdxs,
		MessageInfos:      file_like_what_proto_msgTypes,
	}.Build()
	File_like_what_proto = out.File
	file_like_what_proto_goTypes = nil
	file_like_what_proto_depIdxs = nil
}
